# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft Related
forge_version=43.5.0
minecraft_version = 1.19.2
minecraft_sdk = forge

# Mod Version (for Local Builds Only)
semver = 2.1.3-aelita.1

# Dependency CurseForge Project IDs and File IDs (essentially the file id is synonymous with version number and archive classifier)
markdownmanual_project_id = 502485
markdownmanual_file_id = 4306669
architectury_project_id = 419699
architectury_file_id = 5137942
ccl_project_id = 242818
ccl_file_id = 4965330
cbm_project_id = 258426
cbm_file_id = 4965327

# Dependency Version Info
apache_commons_version = 4.4
jei_version = 11.8.1.1034
pr_version = 4.19.0-beta+33
network_lib_version = 1.0.3
sedna_version = 1.0.57
sedna_version_commit_ref = 6229f4f

# Debug Options
debug_embeddium = false
embeddium_project_id = 908741
embeddium_file_id = 5539178
debug_embeddium_plus_plus = false
embeddium_plus_plus_project_id = 931925
embeddium_plus_plus_file_id = 5344502
debug_oculus = false
oculus_project_id = 581495
oculus_file_id = 6020961

# Repos
native_networking_repo = North-Western-Development/oc2r-native-networking
senda_repo = LadyAelita/sedna-mc-1.19.2

# Test Dependency Versions
mockito_version = 4.3.1
jupiter_version = 5.8.2
